//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvMasterDetails.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public partial class OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetail()
        {
            this.RemarksTables = new HashSet<RemarksTable>();
        }
    
        public int OrderDetailsID { get; set; }
        public System.Guid GUID { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public int Quantity { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual OrderMaster OrderMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemarksTable> RemarksTables { get; set; }
    }
}
