//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvMasterDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemarksTable
    {
        public int RemarkId { get; set; }
        public Nullable<int> OrderDetailsID { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string UpdateTime { get; set; }
        public System.Guid GUID { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
