//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvMasterDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.Guid SecretKey { get; set; }
        public Nullable<bool> AdminType { get; set; }
        public Nullable<System.Guid> GlobalID { get; set; }
        public Nullable<bool> SuperAdmin { get; set; }
        public string ProfilePicPath { get; set; }
        public byte[] imgsrc { get; set; }
        public string Role { get; set; }
        public string contact { get; set; }
        public string State { get; set; }
        public string NotiyMsg { get; set; }
        public string JoiningDate { get; set; }
        public string LastLoginTime { get; set; }
        public Nullable<bool> AccountActive { get; set; }
        public Nullable<decimal> OtpP { get; set; }
        public string UserName { get; set; }
    }
}
